### ISSUE TITLE
make demo more interactive

### ISSUE THREAD

**Issue by NicolasRannou** [lebarba/WebGLVolumeRendering#1]
Hi -

Nice stuff about the volume rendering - I am myself implementing the same thing for medical imaging purposes and I just wanted to suggest you a small modification to you demo which could improve its impact a lot:

When user interacts with the scene (mouse  left button down basically), decrease the number of steps (set to a fixed number or divide target number of steps by 2 or 3) so it is smooth. When the user releases the button, go back to the expected number of steps.

Find here an example:
https://github.com/FNNDSC/vjs/blob/master/examples/shaders_raycasting/shaders_raycasting.js#L22-L32

And here is my dummy raycasting demo of a 896x896x60 voxels (90mB) big dataset. (yellow progress bar  shows the progress of the download)
http://fnndsc.github.io/vjs/#shaders_raycasting

Best,

**Comment by lebarba** [comment]
HI Nicolas!
Thanks! I'll give it a try when I get the chance!

Cheers,
Leandro
