### ISSUE TITLE
Index page doesn't open on macOS

### ISSUE THREAD

**Issue by KalyaniNemala16** [lebarba/WebGLVolumeRendering#7]
I downloaded the zip file and extracted the files on my macOS Mojave. The Index.html file, when opened on the browser, shows a blank page whereas it works fine the Windows OS. Does this only work on Windows OS? What should I do to make it work on macOS?

**Comment by lebarba** [comment]
Yes, it works fine in MacOs. If you want to run locally, you need to have a local web server installed. You can see how to do it here https://threejs.org/docs/#manual/en/introduction/How-to-run-things-locally
